name: "iwslt14-deen-bpe-convSeq2Seq_multihead_resume"

data:
    src: "de"
    trg: "en"
    train: "test/data/iwslt14/train.bpe.32000"
    dev: "test/data/iwslt14/valid.bpe.32000"
    test: "test/data/iwslt14/test.bpe.32000"
    level: "bpe"
    lowercase: True
    max_sent_length: 62
    src_vocab: "test/data/iwslt14/vocab.txt"
    trg_vocab: "test/data/iwslt14/vocab.txt"

testing:
    beam_size: 5
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.999]
    scheduling: "plateau"
    loss: "crossentropy"
    learning_rate: 0.00001
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    batch_size: 1024
    batch_type: "token"
    early_stopping_metric: "eval_metric"
    epochs: 100
    validation_freq: 4000
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/iwslt14_deen_bpe_convSeq2Seq_multihead_resume"
    overwrite: False
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [0, 1, 2, 3, 4]
    keep_last_ckpts: 5
    load_model: "models/iwslt14_deen_bpe_convSeq2Seq_multihead/best.ckpt"


model:
    initializer: "xavier"
    embed_initializer: "normal"
    embed_init_gain: 1.0
    embed_init_weight: 0.1
    init_gain: 1.0
    bias_initializer: "zeros"
    tied_embeddings: True
    tied_softmax: True
    encoder:
        type: "convSeq2Seq"
        num_layers: 9
        embeddings:
            embedding_dim: 512
            scale: True
        hidden_size: 512
        kernel_size: 5
        dropout: 0.1
    decoder:
        type: "convSeq2Seq"
        num_layers: 3
        embeddings:
            embedding_dim: 512
            scale: True
        hidden_size: 512
        kernel_size: 5
        use_multi_head: True
        num_heads: 8
        dropout: 0.1
