name: "transf_dec_only_toy"

data:
    src: "de"
    trg: "en"
    train: "test/data/toy/train"
    dev: "test/data/toy/dev"
    test: "test/data/toy/test"
    level: "word"
    lowercase: False
    max_sent_length: 360
    trg_voc_min_freq: 0
    trg_voc_limit: 30000
    type: "TwoInOne"

testing:
    beam_size: 2
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    adam_betas: [0.9, 0.999]
    scheduling: "plateau"
    loss: "crossentropy"
    learning_rate: 0.0002
    learning_rate_min: 0.00000001
    label_smoothing: 0.1
    weight_decay: 0.0
    batch_size: 10
    batch_type: "sentence"
    epochs: 100
    validation_freq: 200
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/transformer_dec_only_toy"
    overwrite: True
    shuffle: True
    use_cuda: False
    max_output_length: 300
    print_valid_sents: [0, 3, 6, 9]
    keep_last_ckpts: 2

model:
    initializer: "xavier"
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    init_gain: 1.0
    bias_initializer: "zeros"
    tied_embeddings: False
    tied_softmax: True
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 1024
        dropout: 0.1
        use_enc_dec_attention: False